name: speed-dating
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - plotly
  - jupyter
  - statsmodels 
  - notebook
  - ipykernel
  - nbformat
  - pip
  - pip:
      - kaleido
