name: speed-dating
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - plotly
  - jupyter
  - statsmodels 
  - notebook
  - ipykernel
  - nbformat
  - protobuf<4
  - setuptools<71
  - pip
  - pip:
      - kaleido==0.2.1

